import { IconClipboardCheck, IconCreditCard, IconFileAlert, IconPlant2, IconQrcode, IconReportMoney, IconShieldCheck, IconShoppingBag } from "@tabler/icons-react";

export const dashboardKpis = [
  { icon: "users", label: "Thành viên hoạt động", value: "286", change: "+12 người", tone: "green", module: "Hộ dân & thành viên", detail: { title: "Thành viên hoạt động", period: "Từ 01/01 đến 18/08/2026", summary: "286 thành viên thuộc 218 hộ liên kết đang có hồ sơ sản xuất hoặc nghĩa vụ vốn góp còn hiệu lực.", facts: [["Hộ liên kết", "218 hộ"], ["Thành viên mới tháng 08", "12 người"], ["Tỷ lệ cập nhật hồ sơ", "96,5%"], ["Vốn góp đã xác nhận", "6,48 tỷ đồng"]], timeline: [["18/08 · 09:12", "TV-287 Võ Thị Hồng hoàn tất xác thực hồ sơ"], ["17/08 · 15:40", "12 thành viên mới được tổ trưởng duyệt"]] } },
  { icon: "map", label: "Diện tích sản xuất", value: "412,6 ha", change: "+8,4 ha", tone: "blue", module: "Đất đai & GIS", detail: { title: "Diện tích vùng sản xuất", period: "Dữ liệu GIS chốt ngày 18/08/2026", summary: "46 thửa đất đã số hóa, liên kết với thành viên, mùa vụ và trạng thái tiêu chuẩn.", facts: [["Đạt VietGAP", "358,2 ha · 86,8%"], ["Đang chuyển đổi", "21,8 ha · 5,3%"], ["Đến kỳ kiểm tra", "32,4 ha · 7,9%"], ["Tăng trong tháng", "+8,4 ha"]], timeline: [["18/08 · 10:05", "Thửa TD-209 được cập nhật ranh giới 3,1 ha"], ["14/08 · 16:20", "Bổ sung 8,4 ha vùng liên kết Tân Hội"]] } },
  { icon: "tractor", label: "Sản lượng vụ Hè Thu", value: "2.684 tấn", change: "82% kế hoạch", tone: "amber", module: "Sản xuất", detail: { title: "Sản lượng vụ Hè Thu 2026", period: "Cập nhật thu hoạch đến 18/08/2026", summary: "Sản lượng đã nghiệm thu từ 38/46 thửa; phần còn lại là sản lượng dự kiến theo lịch thu hoạch đã xác nhận.", facts: [["Kế hoạch mùa vụ", "3.274 tấn"], ["Đã nghiệm thu", "2.684 tấn"], ["Chờ nghiệm thu", "332 tấn"], ["Chênh lệch dự báo", "-258 tấn · do thời tiết"]], timeline: [["18/08 · 11:30", "Nghiệm thu 12,6 tấn sầu riêng khu Tân Thuận"], ["17/08 · 17:15", "Điều chỉnh dự báo xoài Bình Hòa sau kiểm tra vườn"]] } },
  { icon: "money", label: "Doanh thu lũy kế", value: "18,42 tỷ", change: "+14,8%", tone: "purple", module: "Tài chính", detail: { title: "Doanh thu lũy kế", period: "01/01 - 18/08/2026", summary: "Doanh thu đã ghi nhận từ phiếu thu, hợp đồng và đơn giao hàng hoàn tất; chưa bao gồm các đơn chờ xác nhận.", facts: [["Đã đối soát", "16,98 tỷ đồng"], ["Chờ thanh toán", "1,06 tỷ đồng"], ["Công nợ quá hạn", "62,8 triệu đồng"], ["So với cùng kỳ", "+14,8%"]], timeline: [["18/08 · 14:20", "Ghi nhận PT-0826-107: 186,5 triệu đồng"], ["15/08 · 09:10", "Gửi nhắc đối soát công nợ GreenMart"]] } },
];

export const cropProgress = [
  { name: "Sầu riêng Ri6", amount: "1.120 tấn", pct: 88, color: "#2d7a4f", area: "183,4 ha", plan: "1.280 tấn", harvest: "22/08 - 18/09", module: "Sản xuất" },
  { name: "Xoài cát Hòa Lộc", amount: "684 tấn", pct: 76, color: "#d99c2b", area: "96,2 ha", plan: "900 tấn", harvest: "Đang thu hoạch", module: "Sản xuất" },
  { name: "Bưởi da xanh", amount: "428 tấn", pct: 69, color: "#4b82c3", area: "72,1 ha", plan: "620 tấn", harvest: "05/09 - 28/09", module: "Sản xuất" },
  { name: "Chanh không hạt & khác", amount: "452 tấn", pct: 61, color: "#9187d9", area: "60,9 ha", plan: "740 tấn", harvest: "Theo lịch từng tổ", module: "Sản xuất" },
];

export const orderSnapshot = [
  { code: "DH-0826-41", customer: "Công ty An Phú", product: "Sầu riêng Ri6 loại A", quantity: "8.500 kg", delivery: "19/08/2026", status: "Chờ xác nhận", value: "765.000.000 đ" },
  { code: "DH-0826-39", customer: "GreenMart", product: "Bưởi da xanh", quantity: "2.100 kg", delivery: "20/08/2026", status: "Đang đóng gói", value: "119.700.000 đ" },
  { code: "DH-0826-37", customer: "Nông sản Việt Xanh", product: "Xoài cát Hòa Lộc", quantity: "3.600 kg", delivery: "21/08/2026", status: "Đã xếp lịch xe", value: "162.000.000 đ" },
];

export const activities = [
  { icon: IconPlant2, title: "Nhật ký canh tác được cập nhật", sub: "TD-042 · Bón phân hữu cơ giai đoạn nuôi trái", time: "18 phút trước", tone: "green", module: "Sản xuất", detail: { title: "Nhật ký TD-042 · Bón phân hữu cơ", description: "Ông Nguyễn Văn Thành ghi nhận bón 320 kg phân hữu cơ vi sinh cho 2,4 ha sầu riêng Ri6. Bản ghi đang chờ tổ trưởng xác nhận.", facts: [["Mã nhật ký", "NK-TD042-0818"], ["Vật tư", "Phân hữu cơ vi sinh · 320 kg"], ["Người thực hiện", "Nguyễn Văn Thành · TV-102"], ["Thời gian cách ly", "Không áp dụng"]], timeline: [["10:42", "Thành viên gửi nhật ký kèm 02 ảnh hiện trường"], ["10:47", "Hệ thống kiểm tra vật tư nằm trong danh mục đã khai báo"], ["Chờ xử lý", "Tổ trưởng vùng Tân Thuận xác nhận"]] } },
  { icon: IconShoppingBag, title: "Đơn hàng mới cần xác nhận", sub: "DH-0826-41 · Công ty An Phú · 8.500 kg", time: "42 phút trước", tone: "amber", module: "Kho & tiêu thụ", detail: { title: "Đơn DH-0826-41", description: "Công ty An Phú đặt 8.500 kg sầu riêng Ri6 loại A, giao tại kho lạnh số 1 trước 16:00 ngày 19/08/2026.", facts: [["Giá trị tạm tính", "765.000.000 đ"], ["Đặt cọc", "30% · chờ xác nhận"], ["Nguồn dự kiến", "SR-2408-16 và 06 lô thu hoạch"], ["Điều kiện giao", "Độ Brix ≥ 20 · QR đầy đủ"]], timeline: [["10:18", "Khách hàng gửi đơn điện tử"], ["10:21", "Hệ thống đối chiếu tồn kho khả dụng: 9.240 kg"], ["Trước 14:00", "Cán bộ kinh doanh cần xác nhận đơn"]] } },
  { icon: IconQrcode, title: "Hoàn tất đóng gói lô SR-2408-16", sub: "1.250 kg · Kho lạnh số 1 · 125 tem QR", time: "2 giờ trước", tone: "blue", module: "Kho & tiêu thụ", detail: { title: "Lô SR-2408-16", description: "Lô sầu riêng Ri6 loại A đã hoàn tất phân loại, đóng gói và kích hoạt 125 tem QR truy xuất.", facts: [["Nguồn thu hoạch", "TD-042, TD-044, TD-071"], ["Khối lượng nhập", "1.310 kg"], ["Hao hụt sơ chế", "60 kg · 4,6%"], ["Hạn bảo quản", "21/08/2026 · 17:00"]], timeline: [["08:10", "Nhập kho và kiểm tra ngoại quan"], ["08:55", "Đóng 125 thùng x 10 kg"], ["09:06", "Kích hoạt mã QR và bàn giao kho lạnh"]] } },
  { icon: IconReportMoney, title: "Đã đối soát thanh toán", sub: "HĐ-2026-081 · 186.500.000 đ · đã hạch toán", time: "Hôm qua", tone: "purple", module: "Tài chính", detail: { title: "Đối soát HĐ-2026-081", description: "Khoản phải thu từ Công ty Minh Phát đã khớp sao kê ngân hàng và được hạch toán vào phiếu PT-0826-107.", facts: [["Giá trị hợp đồng", "186.500.000 đ"], ["Số tiền nhận", "186.500.000 đ"], ["Tài khoản nhận", "HTX Tân Thuận · Vietcombank"], ["Trạng thái", "Đã đối soát"]], timeline: [["16:08 · 17/08", "Nhận báo có ngân hàng"], ["16:20 · 17/08", "Kế toán đính kèm sao kê"], ["09:05 · 18/08", "Quản trị viên phê duyệt hạch toán"]] } },
];

export const alerts = [
  { title: "03 thửa sắp đến kỳ kiểm tra", detail: "TD-042, TD-118, TD-209 cần rà soát VietGAP trước 25/08", module: "Đất đai & GIS", detailData: { title: "Kế hoạch kiểm tra VietGAP", description: "Ba thửa có chứng nhận VietGAP đến kỳ giám sát nội bộ. Hồ sơ cần có nhật ký canh tác, danh mục vật tư, ảnh hiện trường và biên bản kiểm tra.", facts: [["TD-042", "22/08 · Tân Thuận · 2,4 ha"], ["TD-118", "23/08 · Bình Hòa · 1,8 ha"], ["TD-209", "25/08 · An Phú · 3,1 ha"], ["Phụ trách", "Tổ kiểm soát chất lượng HTX"]], timeline: [["Hôm nay", "Gửi nhắc lịch và checklist hồ sơ"], ["22-25/08", "Kiểm tra hiện trường theo kế hoạch"], ["Trong 24 giờ", "Lập biên bản, đóng hoặc mở hành động khắc phục"]] } },
  { title: "Lô hàng SR-2408-16 sắp hết hạn", detail: "1.250 kg tại kho lạnh số 1 · còn 3 ngày bảo quản", module: "Kho & tiêu thụ", detailData: { title: "Lô SR-2408-16 cần ưu tiên xuất kho", description: "Nhiệt độ kho ghi nhận 13,2°C, độ ẩm 85%. Lô đủ điều kiện giao nhưng cần được xếp chuyến trước 17:00 ngày 21/08/2026.", facts: [["Tồn khả dụng", "1.250 kg"], ["Khách hàng gợi ý", "Công ty An Phú"], ["Nhiệt độ kho", "13,2°C"], ["Giới hạn bảo quản", "21/08/2026 · 17:00"]], timeline: [["18/08 · 08:10", "Đã nhập kho"], ["19/08", "Ưu tiên phân bổ cho DH-0826-41"], ["21/08", "Cảnh báo mức nghiêm trọng nếu chưa xuất"]] } },
  { title: "02 công nợ quá hạn", detail: "GreenMart và Đại Phúc · cần đối soát 62,8 triệu đồng", module: "Tài chính", detailData: { title: "Công nợ cần đối soát", description: "Hai khoản phải thu đã quá hạn thanh toán theo điều khoản hợp đồng. Cần xác nhận công nợ, lập lịch thu hoặc mở xử lý tranh chấp.", facts: [["GreenMart · CN-0826-019", "48.300.000 đ · quá hạn 6 ngày"], ["Đại Phúc · CN-0826-014", "14.500.000 đ · quá hạn 2 ngày"], ["Tổng quá hạn", "62.800.000 đ"], ["Người phụ trách", "Nguyễn Minh Tâm"]], timeline: [["15/08", "Đã gửi email nhắc GreenMart"], ["17/08", "Đại Phúc xác nhận đang xử lý chứng từ"], ["Hôm nay", "Cần gọi đối soát và cập nhật cam kết thanh toán"]] } },
];

export const controlChecks = [
  { label: "Nhật ký đúng hạn", value: "184/196", note: "12 bản ghi chờ xác nhận", tone: "green", module: "Sản xuất" },
  { label: "Tem QR đã kích hoạt", value: "8/10 lô", note: "02 lô chờ kiểm nghiệm", tone: "blue", module: "Kho & tiêu thụ" },
  { label: "Hồ sơ đạt chuẩn", value: "6/9", note: "03 thửa đến kỳ kiểm tra", tone: "amber", module: "Hồ sơ & tài liệu" },
  { label: "Đơn hàng đúng SLA", value: "24/27", note: "03 đơn cần xử lý hôm nay", tone: "purple", module: "Kho & tiêu thụ" },
];
