"use client";

import { useState } from "react";
import { IconBell, IconBuildingCommunity, IconCalendarEvent, IconKey, IconMail, IconPhone, IconShieldCheck, IconUserEdit, IconUsers } from "@tabler/icons-react";
import { FormModal, SideSheet, Status } from "./shared-ui";

const activities = [["20/08 · 10:15","Cập nhật cấu hình cảnh báo công nợ","Cấu hình hệ thống"],["19/08 · 16:40","Duyệt phiếu chi PC-0826-058","Tài chính"],["18/08 · 14:20","Phân quyền điều phối vùng Tân Thuận","Hộ dân & thành viên"],["18/08 · 09:30","Xác nhận hồ sơ HS-CL-041","Hồ sơ & tài liệu"]];

export default function ProfileSheet({ onClose, onNotice }) {
  const [tab, setTab] = useState("Thông tin"); const [editing, setEditing] = useState(false); const tabs = ["Thông tin", "Quyền truy cập", "Hoạt động", "Bảo mật"];
  return <SideSheet title="Tài khoản quản trị" onClose={onClose}><div className="profile-sheet"><section className="profile-sheet-head"><div className="profile-sheet-avatar">NT</div><div><span>QUẢN TRỊ HỆ THỐNG</span><h3>Nguyễn Minh Tâm</h3><p>Quản trị vận hành HTX Số Đồng Tháp</p></div><Status value="Đang hoạt động" /></section><div className="profile-sheet-tabs" role="tablist">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Thông tin" && <div className="profile-sheet-content"><dl className="profile-facts"><div><dt><IconMail size={16} />Email công việc</dt><dd>minhtam@htxso.vn</dd></div><div><dt><IconPhone size={16} />Điện thoại</dt><dd>0908 452 168</dd></div><div><dt><IconBuildingCommunity size={16} />Đơn vị mặc định</dt><dd>HTX Nông nghiệp Tân Thuận</dd></div><div><dt><IconCalendarEvent size={16} />Tham gia hệ thống</dt><dd>12/01/2024</dd></div></dl><button className="outline-btn full" onClick={() => setEditing(true)}><IconUserEdit size={16} />Cập nhật thông tin cá nhân</button></div>}
    {tab === "Quyền truy cập" && <div className="profile-sheet-content"><section className="profile-role"><IconShieldCheck size={22} /><div><span>Vai trò chính</span><b>Quản trị HTX</b><small>Quyền quản trị cấu hình và phê duyệt nghiệp vụ theo phạm vi được giao.</small></div></section><div className="profile-permissions"><h4>Phạm vi nghiệp vụ</h4>{[["Cấu hình hệ thống","Toàn quyền"],["Hợp tác xã & thành viên","Toàn quyền"],["Sản xuất, GIS & kho","Xem và phê duyệt"],["Tài chính & hồ sơ","Xem và phê duyệt"]].map(([label,value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="profile-permissions"><h4>Phạm vi dữ liệu</h4><div><span>Đơn vị</span><b>04 HTX đang quản lý</b></div><div><span>Vùng sản xuất</span><b>Toàn bộ 412,6 ha</b></div></div></div>}
    {tab === "Hoạt động" && <div className="profile-sheet-content"><section className="profile-activity"><h4>Hoạt động gần đây</h4>{activities.map(([time,action,module]) => <div key={`${time}-${action}`}><time>{time}</time><p><b>{action}</b><span>{module}</span></p></div>)}</section></div>}
    {tab === "Bảo mật" && <div className="profile-sheet-content"><section className="profile-role"><IconKey size={22} /><div><span>Trạng thái bảo mật</span><b>Xác thực hai lớp đang bật</b><small>Tài khoản yêu cầu mã xác thực bổ sung khi đăng nhập từ thiết bị mới.</small></div></section><div className="profile-permissions"><h4>Phiên và đăng nhập</h4><div><span>Phiên hiện tại</span><b>Hết hạn sau 07 giờ 12 phút</b></div><div><span>Lần đăng nhập gần nhất</span><b>20/08/2026 · 08:12</b></div><div><span>Thiết bị tin cậy</span><b>02 thiết bị</b></div></div><button className="outline-btn full" onClick={() => setEditing(true)}><IconBell size={16} />Cập nhật bảo mật</button></div>}
    {editing && <FormModal title={tab === "Bảo mật" ? "Cập nhật bảo mật tài khoản" : "Cập nhật thông tin cá nhân"} description="Thay đổi được lưu ở trạng thái mô phỏng và ghi nhận vào nhật ký kiểm toán." fields={tab === "Bảo mật" ? [{name:"session",label:"Thời hạn phiên (giờ)",type:"number",value:"8",required:true},{name:"twoFactor",label:"Xác thực hai lớp",type:"select",options:["Bắt buộc","Tùy chọn"],required:true}] : [{name:"name",label:"Họ và tên",value:"Nguyễn Minh Tâm",required:true},{name:"email",label:"Email công việc",type:"email",value:"minhtam@htxso.vn",required:true},{name:"phone",label:"Số điện thoại",type:"tel",value:"0908 452 168",required:true}]} onClose={() => setEditing(false)} onSubmit={() => { setEditing(false); onNotice(); }} />}</div></SideSheet>;
}
