"use client";

import { useEffect, useState } from "react";
import { IconBell, IconBuildingCommunity, IconCalendarEvent, IconKey, IconMail, IconPhone, IconShieldCheck, IconUserEdit, IconUsers } from "@tabler/icons-react";
import { FormModal, SideSheet, Status } from "./shared-ui";
import { apiGet, apiPut } from "../lib/api";

const activities = [["20/08 · 10:15","Cập nhật cấu hình cảnh báo công nợ","Cấu hình hệ thống"],["19/08 · 16:40","Duyệt phiếu chi PC-0826-058","Tài chính"],["18/08 · 14:20","Phân quyền điều phối vùng Tân Thuận","Hộ dân & thành viên"],["18/08 · 09:30","Xác nhận hồ sơ HS-CL-041","Hồ sơ & tài liệu"]];

export default function ProfileSheet({ onClose, onNotice }) {
  const [tab, setTab] = useState("Thông tin"); const [editing, setEditing] = useState(false); const [user, setUser] = useState(null); const [role, setRole] = useState(null); const [activities, setActivities] = useState([]); const [error, setError] = useState(""); const tabs = ["Thông tin", "Quyền truy cập", "Hoạt động", "Bảo mật"];
  useEffect(() => { let active = true; Promise.all([apiGet("/api/users/USR-001"), apiGet("/api/roles/ADMIN"), apiGet("/api/auditEvents?cooperativeCode=HTX-001")]).then(([userResult, roleResult, auditResult]) => { if (!active) return; setUser(userResult.data); setRole(roleResult.data); setActivities(auditResult.data.map((item) => [new Intl.DateTimeFormat("vi-VN", { dateStyle:"short", timeStyle:"short" }).format(new Date(item.createdAt)), item.action, item.entity || "Hệ thống"])); }).catch((reason) => active && setError(reason.message)); return () => { active = false; }; }, []);
  const displayName = user?.name || "Đang tải"; const initials = displayName.split(" ").filter(Boolean).slice(-2).map((item) => item[0]).join("");
  return <SideSheet title="Tài khoản quản trị" onClose={onClose}><div className="profile-sheet">{error && <p className="data-source-error">Không thể tải hồ sơ tài khoản: {error}</p>}<section className="profile-sheet-head"><div className="profile-sheet-avatar">{initials}</div><div><span>HỒ SƠ NGƯỜI DÙNG</span><h3>{displayName}</h3><p>{role?.name || user?.roleCode || "Chưa gán vai trò"}</p></div><Status value={user?.status === "active" ? "Đang hoạt động" : user?.status || "Đang tải"} /></section><div className="profile-sheet-tabs" role="tablist">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Thông tin" && <div className="profile-sheet-content"><dl className="profile-facts"><div><dt><IconMail size={16} />Email công việc</dt><dd>{user?.email || "Chưa cập nhật"}</dd></div><div><dt><IconPhone size={16} />Điện thoại</dt><dd>{user?.phone || "Chưa cập nhật"}</dd></div><div><dt><IconBuildingCommunity size={16} />Đơn vị mặc định</dt><dd>{user?.cooperativeCode || "Chưa cập nhật"}</dd></div><div><dt><IconCalendarEvent size={16} />Tạo tài khoản</dt><dd>{user?.createdAt ? new Intl.DateTimeFormat("vi-VN").format(new Date(user.createdAt)) : "Chưa cập nhật"}</dd></div></dl><button className="outline-btn full" onClick={() => setEditing(true)}><IconUserEdit size={16} />Cập nhật thông tin cá nhân</button></div>}
    {tab === "Quyền truy cập" && <div className="profile-sheet-content"><section className="profile-role"><IconShieldCheck size={22} /><div><span>Vai trò chính</span><b>{role?.name || user?.roleCode || "Chưa gán"}</b><small>Phạm vi quyền được đọc từ vai trò được gán cho tài khoản.</small></div></section><div className="profile-permissions"><h4>Phạm vi nghiệp vụ</h4>{(role?.permissions || []).map((permission) => <div key={permission}><span>{permission}</span><b>{role.scope || "cooperative"}</b></div>)}</div><div className="profile-permissions"><h4>Phạm vi dữ liệu</h4><div><span>Đơn vị</span><b>{user?.cooperativeCode || "Chưa gán"}</b></div></div></div>}
    {tab === "Hoạt động" && <div className="profile-sheet-content"><section className="profile-activity"><h4>Hoạt động gần đây</h4>{activities.map(([time,action,module]) => <div key={`${time}-${action}`}><time>{time}</time><p><b>{action}</b><span>{module}</span></p></div>)}</section></div>}
    {tab === "Bảo mật" && <div className="profile-sheet-content"><section className="profile-role"><IconKey size={22} /><div><span>Trạng thái bảo mật</span><b>Xác thực hai lớp đang bật</b><small>Tài khoản yêu cầu mã xác thực bổ sung khi đăng nhập từ thiết bị mới.</small></div></section><div className="profile-permissions"><h4>Phiên và đăng nhập</h4><div><span>Phiên hiện tại</span><b>Hết hạn sau 07 giờ 12 phút</b></div><div><span>Lần đăng nhập gần nhất</span><b>20/08/2026 · 08:12</b></div><div><span>Thiết bị tin cậy</span><b>02 thiết bị</b></div></div><button className="outline-btn full" onClick={() => setEditing(true)}><IconBell size={16} />Cập nhật bảo mật</button></div>}
    {editing && <FormModal title={tab === "Bảo mật" ? "Cập nhật bảo mật tài khoản" : "Cập nhật thông tin cá nhân"} description="Thay đổi được cập nhật trực tiếp trên hồ sơ người dùng." fields={tab === "Bảo mật" ? [{name:"session",label:"Thời hạn phiên (giờ)",type:"number",value:"8",required:true},{name:"twoFactor",label:"Xác thực hai lớp",type:"select",options:["Bắt buộc","Tùy chọn"],required:true}] : [{name:"name",label:"Họ và tên",value:user?.name || "",required:true},{name:"email",label:"Email công việc",type:"email",value:user?.email || "",required:true},{name:"phone",label:"Số điện thoại",type:"tel",value:user?.phone || "",required:true}]} onClose={() => setEditing(false)} onSubmit={async (values) => { try { if (tab !== "Bảo mật") { const result = await apiPut("/api/users/USR-001", values); setUser(result.data); } setEditing(false); onNotice(); } catch (reason) { setError(reason.message); } }} />}</div></SideSheet>;
}
