"use client";

import { useState } from "react";
import { IconAdjustmentsHorizontal, IconArrowUpRight, IconSearch, IconX } from "@tabler/icons-react";

export function ModuleHero({ icon: Icon, eyebrow, title, description, actionLabel, onAction }) {
  return <div className="module-hero"><div className="module-symbol"><Icon size={23} /></div><div><p>{eyebrow}</p><h2>{title}</h2><span>{description}</span></div><button className="primary-btn module-add" onClick={onAction}>{actionLabel}</button></div>;
}
export function SummaryStats({ stats }) { return <div className="module-stats">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>; }
export function Status({ value }) { const style = value.includes("Quá") || value.includes("Sắp") || value.includes("Cần") ? "warn" : value.includes("Chờ") || value.includes("Đang") ? "pending" : "ok"; return <span className={`status ${style}`}>{value}</span>; }
export function DataTable({ columns, rows, query, onQueryChange, filterOpen, onFilterToggle, onRowClick }) {
  const [statusFilter, setStatusFilter] = useState("Tất cả");
  const filteredRows = rows.filter((row) => {
    if (statusFilter === "Tất cả") return true;
    return statusFilter === "Đang xử lý" ? /Đang|Chờ/.test(row.at(-1)) : /Quá|Sắp|Cần/.test(row.at(-1));
  });
  return <div className="panel data-panel"><div className="data-toolbar"><label className="data-search"><IconSearch size={17} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Tìm theo mã, tên hoặc trạng thái" aria-label="Tìm kiếm dữ liệu" /></label><button className={filterOpen ? "filter-btn selected" : "filter-btn"} onClick={onFilterToggle}><IconAdjustmentsHorizontal size={17} />Bộ lọc</button></div>{filterOpen && <div className="filter-panel"><span>Trạng thái</span>{["Tất cả", "Đang xử lý", "Cần lưu ý"].map((filter) => <button key={filter} className={statusFilter === filter ? "filter-chip active" : "filter-chip"} onClick={() => setStatusFilter(filter)}>{filter}</button>)}</div>}<div className="table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}<th /></tr></thead><tbody>{filteredRows.map((row) => <tr key={row[0]} onClick={() => onRowClick(row)}>{row.map((cell, index) => <td key={index}>{index === row.length - 1 ? <Status value={cell} /> : cell}</td>)}<td><button className="row-action" aria-label={`Xem ${row[0]}`} onClick={(event) => { event.stopPropagation(); onRowClick(row); }}><IconArrowUpRight size={16} /></button></td></tr>)}</tbody></table>{!filteredRows.length && <div className="empty-state">Không có dữ liệu phù hợp với bộ lọc.</div>}</div><footer className="table-footer"><span>Hiển thị {filteredRows.length} bản ghi</span><div><button disabled aria-label="Trang trước">‹</button><b>1</b><button disabled aria-label="Trang sau">›</button></div></footer></div>;
}
export function SideSheet({ title, children, onClose }) { return <div className="sheet-layer" role="dialog" aria-modal="true" aria-label={title}><button className="sheet-backdrop" aria-label="Đóng chi tiết" onClick={onClose} /><aside className="side-sheet"><header><div><span>CHI TIẾT BẢN GHI</span><h3>{title}</h3></div><button aria-label="Đóng" onClick={onClose}><IconX size={19} /></button></header>{children}</aside></div>; }
export function ActionModal({ title, description, onClose, onConfirm, confirmLabel = "Xác nhận" }) { return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-backdrop" aria-label="Đóng" onClick={onClose} /><div className="action-modal"><h3>{title}</h3><p>{description}</p><div><button className="outline-btn" onClick={onClose}>Hủy</button><button className="primary-btn" onClick={onConfirm}>{confirmLabel}</button></div></div></div>; }
export function FormModal({ title, description, fields, onClose, onSubmit, submitLabel = "Lưu" }) { const initial = Object.fromEntries(fields.map((field) => [field.name, field.value || ""])); const [values, setValues] = useState(initial); const [submitting, setSubmitting] = useState(false); return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-backdrop" aria-label="Đóng biểu mẫu" onClick={onClose} /><form className="form-modal" onSubmit={async (event) => { event.preventDefault(); setSubmitting(true); try { await onSubmit(values); } finally { setSubmitting(false); } }}><header><div><span>BIỂU MẪU NGHIỆP VỤ</span><h3>{title}</h3><p>{description}</p></div><button type="button" aria-label="Đóng" onClick={onClose}><IconX size={19} /></button></header><div className="form-grid">{fields.map((field) => <label key={field.name} className={field.wide ? "wide-field" : ""}><span>{field.label}{field.required && <b>*</b>}</span>{field.type === "select" ? <select required={field.required} value={values[field.name]} onChange={(event) => setValues({...values, [field.name]:event.target.value})}>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.required} type={field.type || "text"} value={values[field.name]} placeholder={field.placeholder} onChange={(event) => setValues({...values, [field.name]:event.target.value})} />}</label>)}</div><footer><button type="button" className="outline-btn" onClick={onClose}>Hủy</button><button className="primary-btn" disabled={submitting} type="submit">{submitting ? "Đang lưu…" : submitLabel}</button></footer></form></div>; }
